### ISSUE TITLE
Crash when creating a resource from import block

### ISSUE THREAD

**Issue by sco-at-scg** [segmentio/terraform-provider-segment#52]
**Description**

Crash when creating a resource from import block

```
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-segment_v0.1.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x1024c9248]

goroutine 205 [running]:
github.com/segmentio/terraform-provider-segment/internal/provider/models.(*DestinationMetadataState).getActions(0x140001f47e0?, {0x14000170f00?, 0x6, 0x14000a97b50?})
        github.com/segmentio/terraform-provider-segment/internal/provider/models/destination_metadata.go:292 +0x178
github.com/segmentio/terraform-provider-segment/internal/provider/models.(*DestinationMetadataState).Fill(_, {{0x14000038ff0, 0x18}, {0x140005bae40, 0x1a}, {0x140005ea4e0, 0x2e}, {0x14000039008, 0x13}, {{0x140009544c0, ...}, ...}, ...})
        github.com/segmentio/terraform-provider-segment/internal/provider/models/destination_metadata.go:401 +0x170
github.com/segmentio/terraform-provider-segment/internal/provider/models.(*DestinationState).Fill(0x14000272380, 0x14000bacfe0)
        github.com/segmentio/terraform-provider-segment/internal/provider/models/destination.go:31 +0x7c
github.com/segmentio/terraform-provider-segment/internal/provider.(*destinationResource).Read(0x1400056e408, {0x102aede40, 0x14000510b40}, {{{{0x102af21b8, 0x14000593260}, {0x1029bd840, 0x140005dddd0}}, {0x102af4bb8, 0x140004ca000}}, 0x140004a4060, ...}, ...)
        github.com/segmentio/terraform-provider-segment/internal/provider/destination_resource.go:601 +0x338
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0x140002214a0, {0x102aede40, 0x14000510b40}, 0x14000510bd0, 0x14000bad5e0)
        github.com/hashicorp/terraform-plugin-framework@v1.4.0/internal/fwserver/server_readresource.go:101 +0x4a4
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0x140002214a0, {0x102aede40?, 0x14000510120?}, 0x14000bdc700)
        github.com/hashicorp/terraform-plugin-framework@v1.4.0/internal/proto6server/server_readresource.go:55 +0x1a4
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0x1400021b180, {0x102aede40?, 0x140006e3680?}, 0x140006510e0)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov6/tf6server/server.go:787 +0x3e8
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x102aae720?, 0x1400021b180}, {0x102aede40, 0x140006e3680}, 0x14000472310, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:431 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400028e1e0, {0x102af3278, 0x140002a1a00}, 0x14000a10240, 0x140003f4030, 0x1030b7448, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1360 +0xc88
google.golang.org/grpc.(*Server).handleStream(0x1400028e1e0, {0x102af3278, 0x140002a1a00}, 0x14000a10240, 0x0)
        google.golang.org/grpc@v1.57.0/server.go:1737 +0x82c
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.57.0/server.go:982 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.57.0/server.go:980 +0x16c

Error: The terraform-provider-segment_v0.1.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**To Reproduce**

```terraform
import {
  id = "123"
  to = segment_destination.dest1
}

resource "segment_destination" "dest1" {
  name      = "dest1"
  enabled   = true
  source_id = "456abc"

  metadata = {
    id = "abc123"
  }
  settings = jsonencode({
    "api_key" : "abcd-efgh"
  })
}
```

**Comment by yaeba** [comment]
similar issue, apparently it crashes when the existing destination has non-empty "actions"

**Comment by deanhuynh** [comment]
Thanks for raising our first issue! It should be fixed now 🙂

**Comment by sco-at-scg** [comment]
With the latest commit `ff7bc07`, the issue is still persisting, i.e.: for the destination: **Google Analytics 4** 

```
panic runtime error invalid memory address or nil pointer dereference
[signal SIGSEGV segmentation violation code=0x2 addr=0x8 pc=0x104ca2e3c]

goroutine 73 [running]
github.com/segmentio/terraform-provider-segment/internal/provider/models.(*DestinationMetadataState).getContacts(0x0?, {0x140006799b0?, 0x1, 0x14000528170?})
        //dev/github.com/segmentio/terraform-provider-segment/internal/provider/models/destination_metadata.go240 +0x9c
github.com/segmentio/terraform-provider-segment/internal/provider/models.(*DestinationMetadataState).Fill(_, {{0x14000614408, 0x18}, {0x14000614438, 0x16}, {0x140002ac280, 0x264}, {0x140000383c0, 0x1e}, {{0x1400003c6c0, ...}, ...}, ...})
        //dev/github.com/segmentio/terraform-provider-segment/internal/provider/models/destination_metadata.go412 +0x334
github.com/segmentio/terraform-provider-segment/internal/provider/models.(*DestinationState).Fill(0x1400015e070, 0x1400077f050)
        //dev/github.com/segmentio/terraform-provider-segment/internal/provider/models/destination.go31 +0x8c
github.com/segmentio/terraform-provider-segment/internal/provider.(*destinationResource).Read(0x14000611680, {0x1052b4ea8, 0x140001b1410}, {{{{0x1052b9430, 0x1400061a420}, {0x105176fc0, 0x14000880360}}, {0x1052bc168, 0x140003cea00}}, 0x14000414008, ...}, ...)
        //dev/github.com/segmentio/terraform-provider-segment/internal/provider/destination_resource.go600 +0x2e8
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0x14000181080, {0x1052b4ea8, 0x140001b1410}, 0x140001b14a0, 0x1400077f630)
        /Users/smaskot/go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v1.4.1/internal/fwserver/server_readresource.go101 +0x514
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0x14000181080, {0x1052b4ea8?, 0x140001b12f0?}, 0x14000394740)
        /Users/smaskot/go/pkg/mod/github.com/hashicorp/terraform-plugin-framework@v1.4.1/internal/proto6server/server_readresource.go55 +0x314
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0x140001fc780, {0x1052b4ea8?, 0x140004f6ed0?}, 0x1400059c660)
        /Users/smaskot/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov6/tf6server/server.go787 +0x390
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x105274060?, 0x140001fc780}, {0x1052b4ea8, 0x140004f6ed0}, 0x14000398620, 0x0)
        /Users/smaskot/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go431 +0x164
google.golang.org/grpc.(*Server).processUnaryRPC(0x140001f41e0, {0x1052ba998, 0x140004024e0}, 0x140004fc480, 0x140003420f0, 0x1058c5848, 0x0)
        /Users/smaskot/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go1360 +0xc04
google.golang.org/grpc.(*Server).handleStream(0x140001f41e0, {0x1052ba998, 0x140004024e0}, 0x140004fc480, 0x0)
        /Users/smaskot/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go1737 +0x7c4
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        /Users/smaskot/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go982 +0x84
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 37
        /Users/smaskot/go/pkg/mod/google.golang.org/grpc@v1.57.0/server.go980 +0x154

Error: The terraform-provider-segment.v0.1.0 plugin crashed!
```
